services:
 db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: example
   volumes:
     - postgres-data:/var/lib/postgresql/data
 adminer:
   image: adminer
   restart: always
   ports:
     - 8082:8080
 app:
   build:
     context: .
   ports:
     - 5005:80
   depends_on:
     - db
volumes:
 postgres-data: